/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aexp_samplerecognizer_JNIHelper */

#ifndef _Included_aexp_samplerecognizer_JNIHelper
#define _Included_aexp_samplerecognizer_JNIHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aexp_samplerecognizer_JNIHelper
 * Method:    nativeDistance
 * Signature: ([SI[SI)I
 */
JNIEXPORT jint JNICALL Java_aexp_samplerecognizer_JNIHelper_nativeDistance
  (JNIEnv *, jclass, jshortArray, jint, jshortArray, jint);

/*
 * Class:     aexp_samplerecognizer_JNIHelper
 * Method:    nativeDistanceScriptC
 * Signature: ([SI[SILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_aexp_samplerecognizer_JNIHelper_nativeDistanceScriptC
  (JNIEnv *, jclass, jshortArray, jint, jshortArray, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
